### ISSUE TITLE
[BUG] thread '<unnamed>' panicked at 'not within a catch_unsafe_unwind scope', lib/runtime-core/src/fault.rs:216:10

### ISSUE THREAD

**Issue by MWFIAE** [multiversx/mx-chain-go#4258]
My devnet observer node restarted repeatedly after encountering the following panic:

```
Jul 01 19:31:35 Elrond node[28149]: thread '<unnamed>' panicked at 'not within a catch_unsafe_unwind scope', lib/runtime-core/src/fault.rs:216:10
Jul 01 19:31:35 Elrond node[28149]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jul 01 19:31:35 Elrond node[28149]: fatal runtime error: failed to initiate panic, error 5
Jul 01 19:31:35 Elrond node[28149]: SIGABRT: abort
Jul 01 19:31:35 Elrond node[28149]: PC=0x7fd4089dd7bb m=35 sigcode=18446744073709551610
Jul 01 19:31:35 Elrond node[28149]: goroutine 35989 [running]:
Jul 01 19:31:35 Elrond node[28149]: runtime: unknown pc 0x7fd4089dd7bb
Jul 01 19:31:35 Elrond node[28149]: stack: frame={sp:0xc01db1f230, fp:0x0} stack=[0xc014794000,0xc014796000)
Jul 01 19:31:35 Elrond node[28149]: runtime: unknown pc 0x7fd4089dd7bb
Jul 01 19:31:35 Elrond node[28149]: stack: frame={sp:0xc01db1f230, fp:0x0} stack=[0xc014794000,0xc014796000)
Jul 01 19:31:35 Elrond node[28149]: created by net/http.(*Server).Serve
Jul 01 19:31:35 Elrond node[28149]:         /usr/local/go/src/net/http/server.go:3034 +0x4e8
Jul 01 19:31:35 Elrond node[28149]: goroutine 1 [select, 6 minutes]:
Jul 01 19:31:35 Elrond node[28149]: github.com/ElrondNetwork/elrond-go/node.waitForSignal(0x264e878, 0xc001370000, {0x7fd3b2337068, 0xc001370000}, {0x26405e0, 0xc01017dd10}, {0x2675390, 0xc002a18c60}, 0xc002bd0820, 0x4)
Jul 01 19:31:35 Elrond node[28149]:         /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/node/nodeRunner.go:761 +0xe5
Jul 01 19:31:35 Elrond node[28149]: github.com/ElrondNetwork/elrond-go/node.(*nodeRunner).executeOneComponentCreationCycle(0xc015779b10, 0x200000001)
Jul 01 19:31:35 Elrond node[28149]:         /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/node/nodeRunner.go:475 +0x1ad6
Jul 01 19:31:35 Elrond node[28149]: github.com/ElrondNetwork/elrond-go/node.(*nodeRunner).startShufflingProcessLoop(0xc0008dcbd0, 0x268d710)
Jul 01 19:31:35 Elrond node[28149]:         /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/node/nodeRunner.go:196 +0x65
Jul 01 19:31:35 Elrond node[28149]: github.com/ElrondNetwork/elrond-go/node.(*nodeRunner).Start(0xc00139fb10)
Jul 01 19:31:35 Elrond node[28149]:         /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/node/nodeRunner.go:107 +0x345
Jul 01 19:31:35 Elrond node[28149]: main.startNodeRunner(0x8dc7cb, {0x269e9a0, 0xc0000a8900}, {0xc000730c40, 0x36})
Jul 01 19:31:35 Elrond node[28149]:         /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/cmd/node/main.go:129 +0x2fc
Jul 01 19:31:35 Elrond node[28149]: main.main.func1(0xc000c72420)
Jul 01 19:31:35 Elrond node[28149]:         /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/cmd/node/main.go:76 +0x30
Jul 01 19:31:35 Elrond node[28149]: github.com/urfave/cli.HandleAction({0x1d4f7c0, 0xc0006bc198}, 0xc000c6a1c0)
Jul 01 19:31:35 Elrond node[28149]:         /home/elrond/go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:524 +0xa8
Jul 01 19:31:35 Elrond node[28149]: github.com/urfave/cli.(*App).Run(0xc000c6a1c0, {0xc0000d0000, 0x8, 0x8})
Jul 01 19:31:35 Elrond node[28149]:         /home/elrond/go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:286 +0x625
Jul 01 19:31:35 Elrond node[28149]: main.main()
Jul 01 19:31:35 Elrond node[28149]:         /home/elrond/go/src/github.com/ElrondNetwork/elrond-go/cmd/node/main.go:79 +0x365
Jul 01 19:31:35 Elrond node[28149]: goroutine 21 [select, 10 minutes]:
Jul 01 19:31:35 Elrond node[28149]: github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc000197500)
Jul 01 19:31:35 Elrond node[28149]:         /home/elrond/go/pkg/mod/github.com/ipfs/go-log@v1.0.5/writer/writer.go:71 +0x110
Jul 01 19:31:35 Elrond node[28149]: created by github.com/ipfs/go-log/writer.NewMirrorWriter
Jul 01 19:31:35 Elrond node[28149]:         /home/elrond/go/pkg/mod/github.com/ipfs/go-log@v1.0.5/writer/writer.go:36 +0xcf
```

Full logfile attached 🙏 

[node0_full.zip](https://github.com/ElrondNetwork/elrond-go/files/9030876/node0_full.zip)
<details>

<summary>Executing details</summary>
<pre>
Application version string: D1.3.31.0-0-gde0e7e887/go1.17.6/linux-amd64/537c21cbbf
</pre>
</details>

**Comment by bogdan-rosianu** [comment]
Hello! There is definitely an issue, but we cannot tell for sure because the exception/panic is not caught by golang, therefore we are not able to tell.
Maybe there was an OOM or something like this. 
You can start by setting this flag to `true`:
https://github.com/ElrondNetwork/elrond-go/blob/de0e7e887e63b1675013702922b593fdaa363958/cmd/node/config/config.toml#L686 

WARNING: This is only for debug reasons and should not be used in production
If the node will panic again, you should be able to see what's wrong

**Comment by MWFIAE** [comment]
Hey there,

for now I updated to the pre-release version v1.3.32, after conversation with Iulian Pascalau :)
So not sure I can reproduce the error now (and I don't want to trouble the people playing our closed alpha by introducing the problem again🙏 )

He also mentioned it is related to the fact that I'm using the observer squad to provide an API for the closed alpha, so maybe he can provide more details on that :)
Or maybe the issue can be closed since it seems like it has been fixed with the new version I installed :)
